# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'del_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pymysql
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
import sys

conn =pymysql.connect(
    host='localhost',
    port=3306,
    user="root",
    password='123456',
    database='total',
    charset='utf8'
)

cursor = conn.cursor()

class Del_user(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(311, 469)
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 311, 391))
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(60, 420, 171, 28))
        self.pushButton.setObjectName("pushButton")

        self.model = QStandardItemModel()
        self.model.setHorizontalHeaderLabels(['用户名', '密码'])

        self.tableView.setSelectionBehavior(QAbstractItemView.SelectRows)  # 设置只能选中整行
        self.tableView.setSelectionMode(QAbstractItemView.SingleSelection)  # 设置只能选中一行



        self.pushButton.clicked.connect(Dialog.del_btn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "用户管理"))
        self.pushButton.setText(_translate("Dialog", "删除用户"))

